import Footer from "@/components/organisms/footer";
import AsideBar from "@/components/templates/asidebar";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="grid grid-cols-[1fr_2fr]">
          <AsideBar />
          {children}
        </div>
        <div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
